spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_system?useSSL=false
    username: root
    password: root

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # The SQL dialect makes Hibernate generate better SQL for the chosen database

  #JPA Settings
  jpa.hibernate.ddl_auto: create
management:
  endpoints:
    web:
      exposure:
        include: "health, beans, metrics"

      base-path: "/train-system"

  endpoint:
    health:
      show-details: always

